### ISSUE TITLE
Filter queryset by currently authenticated user

### ISSUE THREAD

**Issue by dagasatvik10** [HackSoftware/Django-Styleguide-Example#314]
Hello @everyone,
I am new to Django and I recently came across this styleguide to develop Django projects and I instantly fell in love with it.

I am facing a slight issue regarding how to filter a queryset using the currently authenticated user stored in `request.user` and also create a reusable base filterset that filters by the current user.
I have looked this up and the solution that I have mostly seen online is to create a custom filter backend. But since this styleguide uses selectors to filter querysets, the above solution will not work.
Can someone please point me in the right direction? Thanks in advance.

**Comment by RadoRado** [comment]
Hello @dagasatvik10 :wave: 

Can you provide an example about where you want to filter that queryset, based on `request.user`? So I can answer you properly.

A code snippet + more explanation would help us point you to the right dirrection.

Cheers!

**Comment by dagasatvik10** [comment]
Hi @RadoRado 

Thanks for the response. Here is an example of how I want to filter the queryset-
```py
# files/models.py
class File(BaseModel):
    file = models.FileField(upload_to=file_generate_upload_path, blank=True, null=True)

    original_file_name = models.TextField()

    file_name = models.CharField(max_length=255, unique=True)
    file_type = models.CharField(max_length=255)

    # As a specific behavior,
    # We might want to preserve files after the uploader has been deleted.
    # In case you want to delete the files too, use models.CASCADE & drop the null=True
    uploaded_by = models.ForeignKey(BaseUser, null=True, on_delete=models.SET_NULL)

    upload_finished_at = models.DateTimeField(blank=True, null=True)

    @property
    def is_valid(self):
        """
        We consider a file "valid" if the the datetime flag has value.
        """
        return bool(self.upload_finished_at)

    @property
    def url(self):
        if settings.FILE_UPLOAD_STORAGE == FileUploadStorage.S3:
            return self.file.url

        return f"{settings.APP_DOMAIN}{self.file.url}"

# files/apis.py
class FileListByCurrentUserApi(ApiAuthMixin, APIView):
    class Pagination(LimitOffsetPagination):
        default_limit = 1

    class FilterSerializer(serializers.Serializer):
        id = serializers.IntegerField(required=False)
        file_type = serializers.CharField(required=False)

    class OutputSerializer(serializers.ModelSerializer):
        class Meta:
            model = File
            fields = ("id", "file_name", "file_type", "url")

    def get(self, request):
        # Make sure the filters are valid, if passed
        filters_serializer = self.FilterSerializer(data=request.query_params)
        filters_serializer.is_valid(raise_exception=True)

       # pass current user to selector
        files = file_list(filters=filters_serializer.validated_data, user=request.user)

        return get_paginated_response(
            pagination_class=self.Pagination,
            serializer_class=self.OutputSerializer,
            queryset=files,
            request=request,
            view=self,
        )

# files/selectors.py
def file_list(*, filters=None, user=None) -> QuerySet[BaseUser]:
    filters = filters or {}

    qs = File.objects.all()

    if user is None:
        return FileFilter(filters, qs).qs

    # filter by the current user
    return FileFilter(filters, qs).qs.filter(user=user)

# files/filters.py
class FileFilter(django_filters.FilterSet):
    class Meta:
        model = File
        fields = ("id", "file_type")
```

But when I was looking online on how to filter by the current user, I came across the following multiple times-
1\. Create a custom filter backend that filters queryset by the current user-
```py
# core/filters.py
from django_filters import rest_framework as filters

class IsOwnerFilterBackend(filters.BaseFilterBackend):
    """
    Filter that only allows users to get their own objects
    """
    def filter_queryset(self, request, queryset, view):
        return queryset.filter(user=request.user)
```
2\. Use the custom filter backend in the API you want to filter queryset by the current user-
```py
# files/apis.py
class FileListByCurrentUserApi(generics.ListAPIView):
    serializer_class = FileSerializer
    queryset = File.objects.all()
    filter_backends = (IsOwnerFilterBackend,)
    filterset_fields = ("user",)
```
So I can use this custom filter backend in any API where I want to filter by the current user. 

But something like this is not possible in the styleguide as it uses selectors. So is my method correct or is there some better way to filter by current user that can be reused by any API?

**Comment by RadoRado** [comment]
Aha, I got it.

There are several options that you can do here:

Give an already filtered queryset to the filters:

```python
def file_list(*, filters=None, user=None) -> QuerySet[BaseUser]:
    filters = filters or {}

    qs = File.objects.all()

    if user is None:
        qs = qs.filter(user=user)
        
    return FileFilter(filters, qs).qs
```

Then, you'll have a limited queryset, to work on, for your filter.

The other thing you can do is to pass the user as part of the filters & have a special filter method for that:

```python
class FileFilter(django_filters.FilterSet):
    user = CharFilter(method="filter_user")

    class Meta:
        model = File
        fields = ("id", "file_type")

    def filter_user(self, queryset, name, value):
        return queryset.filter(user_id=value)
```

And then just pass that:

```python
def file_list(*, filters=None, user=None) -> QuerySet[BaseUser]:
    filters = filters or {}
    if user is not None:
        filters[user] = user.id

...
```

I'd personally go with the first approach - just filter the queryset, before giving it to the filter set.

And of course, I'm not a big fan of giving the request to the filter set, since the filter should operate on querysets & should not care about the request.

Hopefully, this will help you :+1:

**Comment by dagasatvik10** [comment]
Thanks for the clarification @RadoRado.
