### ISSUE TITLE
Render deployment - is it working properly after successful master builds?

### ISSUE THREAD

**Issue by RadoRado** [HackSoftware/Django-Styleguide-Example#331]
We need to double-check that.

**Comment by Ivaylo-Bachvarov** [comment]
It now worked. :tada: https://django-styleguide.hacksoft.io/admin/

**Comment by RadoRado** [comment]
@Ivaylo-Bachvarov - https://github.com/HackSoftware/Django-Styleguide-Example/blob/master/.github/workflows/django.yml#L68
