### ISSUE TITLE
Separate/Hide some endpoints from production?

### ISSUE THREAD

**Issue by milemik** [HackSoftware/Django-Styleguide-Example#338]
Hi I have one question and not sure what is the best approach. Lets say that I have some endpoint that I only need for development/testing purpose. So I don't want this endpoint to be available on PROD environment.

What I did is in settings.base.py - I added flag DEV_OPT = True
```python
# base.py
...
DEV_OPT = True
```
In my settings.prod.py - I set  DEV_OPT = False
```python
# prod.py
...
DEV_OPT = False
```

And in my app.urls.py looks like this:
```python
#app.urls.py
from django.urls import path
from django.conf import settings

urlpatterns = [
    path("", ExampleApi.as_view(), name="example"),
   ...
]

if settings.DEV_OPT:
    urlpatters.append(path("dev_api/", DevApi.as_view(), name="dev_api"))
```

Is there a better/cleaner way of doing this?

My concern is:
**Security**:
1.  since I'm importing all settings from django.conf - so here I'm giving access to all settings variables. Maybe I'm wrong but this gives me a little concern. So **Is it safe to import settings like this**? 

It would be nice to include some solution for this in your StyleGuide which I REALLY REALLY like. 
Thank you for this StyleGuide and for your response in advance :)

**Comment by RadoRado** [comment]
@milemik Hello :wave: 

To answer your questions:

1. It's OK to import your settings like that. As long as you are not running with `DEBUG = True` you'll be fine with your settings.
2. The way you've done it is a good way of doing it. We are using a similar pattern for exposing QA-specific endpoints, for running end-to-end tests.
3. Last but not least, if you are not using something like https://django-environ.readthedocs.io/en/latest/ - consider using it :ok_hand: 

Let me know if you have other questions.

Cheers!

**Comment by milemik** [comment]
Thank you @RadoRado  for fast and clear answer. This completely answers my question.

All the best,
Ivan :)
