### ISSUE TITLE
Handling validation / select depending on request.user question

### ISSUE THREAD

**Issue by rtpm** [HackSoftware/Django-Styleguide-Example#345]
Hello, and thank you for the great Django style guide.

I am reading both style guide and the code and I can't see where would you (or maybe you did?)
put the validation code for web & api (DRF)

For example:
Editing / selecting the object owned (Foreignkey to User model) by user
Checking user permissions for some action.

Should this be specified in the services/selectors (attaching user from the request object)? 
How / where would you return the error ?

Thanks

**Comment by RadoRado** [comment]
Hello @rtpm :wave: 

Application-specific validation should be handled in the service/selector layer :+1: 

How you do it, is of course, up to you & depends on the context of your application.

Feel free to ask further questions, so I can provide more details answers :ok_hand: 

Cheers!

**Comment by RadoRado** [comment]
Closing this issue.

@rtpm if you need additional context / info - feel free to reopen it :+1:
