### ISSUE TITLE
Small Typo in vs is

### ISSUE THREAD

**Issue by mariostg** [HackSoftware/Django-Styleguide-Example#386]
in https://github.com/HackSoftware/Django-Styleguide-Example/blob/master/styleguide_example/common/services.py
Sentence : 
If something **in** present in `fields` 
Should read:
If something **is** present in `fields`

**Comment by RadoRado** [comment]
@mariostg Thank you for spotting this!

And I'm sorry for the late response.

This is now already fixed.

Cheers!
