### ISSUE TITLE
django-celery-beat 2.5.0 depends on Django<5.0 and >=2.2

### ISSUE THREAD

**Issue by EdwinAtieno** [HackSoftware/Django-Styleguide-Example#394]
61.56 INFO: pip is looking at multiple versions of django-celery-beat to determine which version is compatible with other requirements. This could take a while.
61.67 ERROR: Cannot install -r /requirements/base.txt (line 8) and django==5.0.1 because these package versions have conflicting dependencies.
61.67 
61.67 The conflict is caused by:
61.67     The user requested django==5.0.1
61.67     The user requested django==5.0.1
61.67     django-celery-beat 2.5.0 depends on Django<5.0 and >=2.2
61.67 
61.67 To fix this you could try to:
61.67 1. loosen the range of package versions you've specified
61.67 2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by RadoRado** [comment]
@EdwinAtieno I think I fixed this by simply upgrading everything :sweat_smile: 

That's currently on master:

```
$ pip freeze | grep Django
Django==5.0.6

$ pip freeze | grep "django-celery-beat"
django-celery-beat==2.6.0

```

**Comment by EdwinAtieno** [comment]
Hello @RadoRado 
I was able to fix the issue. Thank you.
